### ISSUE TITLE
Header sind nicht dynamisch

### ISSUE THREAD

**Issue by siker102** [hhu-propra2/abschlussprojekt-8head#13]
Auf der Webseite ist der Header, der auf jeder Seite gezeigt wird, komplett statisch. Es macht jedoch keinen Sinn, nicht eingeloggten Nutzern 'Logout' und 'Profil' anzuzeigen, oder eingeloggten Nutzern 'Konto Erstellen' und 'Login' zu zeigen.

Mit Thymeleaf sollte dies verbessert werden. In resources/static/css/style.html findet man den Code für den Header, auf allen Seiten gibt es einen Principal, der null ist, wenn der momentane Nutzer nicht eingeloggt ist, sonst kann man im Controller auf den principal get(principal p) vom PersonService anwenden, um die momentan eingeloggte Person zurückzubekommen. Bei nicht eingeloggten Nutzern gibt get(principal p) null zurück.

Über die Existenz des Principals kann zwischen eingeloggten und nicht-eingeloggten Nutzern unterschieden werden, über person.Rolle.name() kann man zwischen USER und ADMIN unterscheiden.

**Comment by jspinak** [comment]
implemented in bootstrap branch
