### ISSUE TITLE
Konfliktlösungsstelle

### ISSUE THREAD

**Issue by siker102** [hhu-propra2/abschlussprojekt-8head#16]
Wenn sich ausleihende und verleihende Person nicht darüber einig sind, dass eine Kaution
zurückgezahlt wird, zum Beispiel weil ein Gegenstand nicht oder beschädigt zurückgegeben wurde,
wird in der Fall an eine Clearing Stelle übergeben. Die Clearing Stelle kommuniziert außerhalb der
Webanwendung per E-Mail mit den Beteiligten und entscheidet am Ende, wer die Kaution erhält.
Die Entscheidung der Clearingstelle wird in der Anwendung durchgeführt und der Kautionsbetrag
entsprechend gebucht.

Dazu haben wir noch nichts und dies muss noch implementiert werden.

**Comment by u4o** [comment]
Solved by kingfishbrain
