### ISSUE TITLE
Mehrere Konten unter selben Nutzernamen erstellen

### ISSUE THREAD

**Issue by siker102** [hhu-propra2/abschlussprojekt-8head#19]
Man kann momentan mehrere Benutzerkonten unter den selben Nutzernamen erstellen, und Spring Security kommt damit später nicht klar. Man sollte nur ein Konto mit anderem Benutzernamen (username) erstellen können, sonst sollte eine Fehlermeldung oder entsprechende Rückmeldung kommen und der Account nicht erstellt werden.

**Comment by MarvinOh** [comment]
implemented in editProfile branch
