### ISSUE TITLE
In editProfil und register kann man leere Felder eingeben

### ISSUE THREAD

**Issue by MarvinOh** [hhu-propra2/abschlussprojekt-8head#32]
Evtl. sollte man auch Strings abfangen, die nur aus whitespace (spaces/tabs) bestehen, und solche, die null sind

**Comment by MarvinOh** [comment]
In newitem ist dies auch der Fall

**Comment by siker102** [comment]
Problem genauer beschrieben mit genauen Anforderungen in Issue #35
