### ISSUE TITLE
Validator fehlen

### ISSUE THREAD

**Issue by siker102** [hhu-propra2/abschlussprojekt-8head#35]
Momentan kann man Accounts ohne Benutzernamen erstellen, mit leeren Passworten usw. Selbe für Items, und überall wo man Artikel/Personen bearbeiten kann (zB eigenes Profil).
Also brauchen wir Validator, die das kontrollieren können und entsprechende Nachrichten zurückgeben können. Da wir Validator noch nie wirklich gemacht haben, habe ich ein paar Beispiele zur Orientierung gesucht:

Hier ist der UserValidator von https://github.com/hellokoding/registration-login-spring-hsql, einem Projekt was ähnlich wie unseres SpringBoot und SpringBootSecurity verwendet. Es wird zum Registrieren eines Accounts genutzt:

```
import com.hellokoding.auth.model.User;
import com.hellokoding.auth.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;
import org.springframework.validation.Validator;

@Component
public class UserValidator implements Validator {
    @Autowired
    private UserService userService;

    @Override
    public boolean supports(Class<?> aClass) {
        return User.class.equals(aClass);
    }

    @Override
    public void validate(Object o, Errors errors) {
        User user = (User) o;

        ValidationUtils.rejectIfEmptyOrWhitespace(errors, "username", "NotEmpty");
        if (user.getUsername().length() < 6 || user.getUsername().length() > 32) {
            errors.rejectValue("username", "Size.userForm.username");
        }
        if (userService.findByUsername(user.getUsername()) != null) {
            errors.rejectValue("username", "Duplicate.userForm.username");
        }

        ValidationUtils.rejectIfEmptyOrWhitespace(errors, "password", "NotEmpty");
        if (user.getPassword().length() < 8 || user.getPassword().length() > 32) {
            errors.rejectValue("password", "Size.userForm.password");
        }

        if (!user.getPasswordConfirm().equals(user.getPassword())) {
            errors.rejectValue("passwordConfirm", "Diff.userForm.passwordConfirm");
        }
    }
}
```

Es wäre angemessen ein Package in hhu.ausleihservice für validator anzulegen und wie bisher gehabt FieldInjection statt autowired zu nutzen. Im PostMapping von Register sollte userValidator.validate(userForm, bindingResult) die erste Methode sein, die aufgerufen wird. Die verschiedenen Validator kann man im Constructor für den AusleihServiceController als Klassenparameter hinzufügen und über FieldInjection benutzen.

Wie genau die BindingResult Klasse funktioniert, weiß ich nicht ganz, aber sie wird in jedem Beispiel, was ich gefunden habe, benutzt. Hier ist ein Beispiel für eine Controller Methode, die BindingResult benutzt:

```
@RequestMapping(value = "registration", method = RequestMethod.POST)
	public String registration(@ModelAttribute("userForm") AppUser userForm, BindingResult bindingResult, Model model) {
		useraddValidator.validate(userForm, bindingResult);

		if (bindingResult.hasErrors()) {
			return "userregistration";
		}

		userService.save(userForm);

		model.addAttribute("success", "User " + userForm.getUsername() + " created successfully");
		return "success";
	}
```
Quelle: https://github.com/ajkr195/springbootrocks

**Comment by MarvinOh** [comment]
Implemented in add/Validators branch
