### ISSUE TITLE
Items haben zwei felder für bilder

### ISSUE THREAD

**Issue by kingfishbrain** [hhu-propra2/abschlussprojekt-8head#36]
Momentan haben Items zwei Felder zur Bilderspeicherung, "images" und "pictures". Letzteres  speichert das in der Datenbank als byte, das erste als String Datenpfad um Beispielbilder zu speichern. Die String Variente sollte im späteren Verlauf entfernt werden da es irreführend ist ein Feld nur für Beispiel Items zu haben.

**Comment by u4o** [comment]
String variante wurde entfernt. Bilder werden nun in ein Byte Array konvertiert
