### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by u4o** [hhu-propra2/abschlussprojekt-8head#57]
Das Projekt soll "[...]eine Dokumentation enthalten. Diese soll grundlegende Funktionen beschreiben. Es handelt
sich hierbei nicht um ein Protokoll in welchen Schritten Sie was implementiert haben, sondern
soll zur Nachvollziehbarkeit der Entwicklung dienen und die allgemeine Bedienung erklären." Zitat aus Aufgabenstellung

**Comment by MarvinOh** [comment]
> Jede Gruppe muss eine einheitliche Richtlinie bezüglich Codeformatierungen (IDE-
Einstellungen, checkstyle oder pmd) und Commit-Nachrichten festlegen, dokumentieren und
einhalten.
